open-mmlab/mmflow

.readthedocs.yml

[Docs] Add .readthedocs.yml

---

README_zh-CN.md

Update video demo in Chinese README

[Docs] Change video demo for README_zh-CN

---

README.md
README_zh-CN.md

[Docs] Fix invalid link

---

docs/getting_started.md
docs/intro.md

1. revise image link
2. fix script in getting_started

[Doc] Refine documentations

---

README_zh-CN.md

Add MMFlow link in README_zh-CN

[Doc] Add project link in README_zh-CN

---

docs/conf.py
docs_zh-CN/conf.py

1. Add MIM doc link in conf.py
2. Update mmflow doc link.

[Doc] Update docs links of projects in OpenMMLab

---

docs/data_prepare/FlyingChairs/README.md

1. change wegt to wget in docs/data_prepare/FlyingChairs/README.md
fix #20

[Doc] Fix script bug in FlyingChairs dataset prepare

---

docs/index.rst

Set maxdepth = 2 for API Reference in  index.rst

[Docs] Revise index.rst file in docs

---

.github/workflows/build.yml

1. revise .github/workflows/build.yml

[Fix] Delete redundant uploading to codecov

---

configs/flownet/README.md
configs/flownet2/README.md
configs/irr/README.md
configs/liteflownet/README.md
configs/liteflownet2/README.md
configs/maskflownet/README.md
configs/pwcnet/README.md
configs/raft/README.md

Add paper abstract in model README

[Docs] Add Abstract in model README

---

configs/flownet/README.md
configs/flownet2/README.md
configs/irr/README.md
configs/liteflownet/README.md
configs/liteflownet2/README.md
configs/maskflownet/README.md
configs/pwcnet/README.md
configs/raft/README.md

1. Set 70% for images scale in README of model config folders.

[Docs] Resize images in model README

---

README.md
README_zh-CN.md

1. Fix typo in README.md and README_zh-CN.md

[Docs] fix typo in README

---

README.md
README_zh-CN.md
docs/conf.py
docs_zh-CN/conf.py

1. Add project link in README.md and README_zh-CN.md
2. Add docs links in docs/conf.py and docs_zh-CN/conf.py

[Docs] Add MMFewshow project and doc links

---

.github/workflows/build.yml

1. add git in system dependencies

[Enhancement] Fix uploading to codecov

---

configs/flownet2/metafile.yml

1. Fix `In Collection` configs/flownet2/metafile.yml.

[Docs] fix In Collection

---

mmflow/utils/collect_env.py

1. revise `MMOpticalFlow` to `MMFlow` in env_info of mmflow/utils/collect_env.py

[Enhancement]Modify `env_info` key form `MMOpticalflow` to `MMFlow`

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish-to-pypi.yml

Cancel previous runs that are not completed for a given workflow.

[CI] Cancel previous runs that are not completed

---

README.md
mmflow/datasets/pipelines/transforms.py

1. README.md
2. mmflow/datasets/pipelines/transforms.py

[Docs] Refine readme and docstring

---

mmflow/models/utils/correlation_block.py
tests/test_models/test_utils/test_corrblock.py

1. mmflow/models/utils/correlation_block.py
2. tests/test_models/test_utils/test_corrblock.py

[Enhancement] Add `scale_mode` for correlation block

---

docs/en/model_zoo.md
docs/zh_cn/model_zoo.md

[Docs] Fix broken links in model_zoo

---

README.md
README_zh-CN.md
docs/en/model_zoo.md
docs/zh_cn/model_zoo.md

1. Add GMA in model zoo
2. Add MMSelfSup MMRazor MMDeploy in README

[Enhancement] Update README and model_zoo

---

docs/en/tutorials/1_inference.md
docs/en/tutorials/2_finetune.md
mmflow/apis/train.py
tools/test.py
tools/train.py

ref: https://github.com/open-mmlab/mmcv/pull/1621 and https://github.com/open-mmlab/mmdetection/pull/7016

[Enhancement]Support CPU Train/Inference

---

README.md

I guess you mean Jan 07, 2022 : )

Date format in readme

---

configs/gma/README.md

[Fix] Fix broken URLs in GMA README

---

.github/workflows/build.yml
mmflow/datasets/flyingthings3d_subset.py
requirements/runtime.txt
requirements/tests.txt
tests/test_datasets/test_datasets.py
tests/test_utils/test_misc.py
tests/test_utils/test_set_env.py

- Add win-ci in .github/workflows/build.yml
ref pr: https://github.com/open-mmlab/mmediting/pull/732

[Enhancement] Add win-ci

---

README.md
README_zh-CN.md

As title
ref: https://github.com/open-mmlab/mmdetection/pull/7239

[Docs]Reorganizing OpenMMLab projects in readme

---

mmflow/models/losses/__init__.py
mmflow/models/losses/ssim.py
tests/test_models/test_losses.py

as tittle
- add `weighted_ssim` function in mmflow/models/losses/ssim.py and its UT

[Features] Add SISS loss function

---

README.md
README_zh-CN.md
docs/en/changelog.md
mmflow/version.py

Bump version to v0.4.0

---

mmflow/datasets/pipelines/loading.py
mmflow/datasets/utils/__init__.py
mmflow/datasets/utils/flow_io.py
tests/test_datasets/test_datasets_utils.py

1. add `flow_from_bytes` in mmflow/datasets/utils/flow_io.py
2. add decoding bytes function for `read_pfm`

[Features]Loading flow annotation from file client

---

mmflow/__init__.py
requirements/mminstall.txt

as title
1. mmflow/__init__.py
2. requirements/mminstall.txt

[Enhancement] MMCV maximum_version set to 1.6

---

tools/prepare_datasets/prepare_flyingchairs.py

It is for generating samples filename of flyingchairs dataset
Add  tools/prepare_datasets/prepare_flyingchairs.py

[Feature] Generate ann_file for flyingchairs

---

.github/workflows/build.yml

related pr  #https://github.com/open-mmlab/mmocr/pull/988

[Fix] Add GPG keys in CI

---

docs/en/tutorials/0_config.md
docs/zh_cn/tutorials/0_config_.md

Fix a typo in en_docs 0_config.md

[Docs] add zh-cn doc 0_config_.md

---

README.md
README_zh-CN.md
docs/en/changelog.md
mmflow/version.py

Bump version to v0.4.1

---

README.md
README_zh-CN.md

[Doc] Format README

---

README.md
README_zh-CN.md

[Doc] Fix README

---

configs/pwcnet/metafile.yml

fix https://github.com/open-mmlab/mmflow/issues/149

[fix] fix config file error in metafile (#149)

---

setup.py

ref https://github.com/open-mmlab/mmsegmentation/pull/1655

Add mim to extras_require in setup.py

---

.github/workflows/lint.yml
.pre-commit-config.yaml

ref https://github.com/open-mmlab/mmcv/pull/2014

[Docs] Fix mdformat version to support python3.6 and remove ruby install

---

configs/gma/metafile.yml

Modified for Issue #156

---

mmflow/__init__.py
requirements/mminstall.txt

1. mmflow/\_\_init\_\_.py
2. requirements/mminstall.txt
ref: https://github.com/open-mmlab/mmsegmentation/pull/1764

[Enhancement] MMCV maximum_version set to 1.7

---

mmflow/engine/__init__.py

1. Fix import visualization
1. mmflow/engine/__init__.py
**Before PR**:
**After PR**:

[Fix] Fix visualization imports

---

.circleci/config.yml
.circleci/docker/Dockerfile
.circleci/test.yml

Please describe the motivation of this PR and the goal you want to achieve through this PR.
Please briefly describe what modification is made in this PR.
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before …

[Enhancement] Add CircleCI

---

mmflow/engine/hooks/liteflownet_stage_loading.py
tests/test_engine/test_hook/test_liteflownet_stage_loading.py

Meet the requirements of MMFlow2.0.
1. mmflow/engine/hooks/liteflownet_stage_loading.py
2. tests/test_engine/test_hook/test_liteflownet_stage_loading.py

[Refactor] liteflownet_stage_loading

---

configs/_base_/models/flownet2/flownet2.py
configs/_base_/models/flownet2/flownet2cs.py
configs/_base_/models/flownet2/flownet2css-sd.py
configs/_base_/models/flownet2/flownet2css.py
configs/_base_/models/flownet2/flownet2sd.py
configs/_base_/models/flownetc.py
configs/_base_/models/flownets.py
configs/_base_/models/irrpwc.py
configs/_base_/models/liteflownet/liteflownet_pre_M2S2R2.py
configs/_base_/models/liteflownet/liteflownet_pre_M3S3R3.py
configs/_base_/models/liteflownet/liteflownet_pre_M4S4R4.py
configs/_base_/models/liteflownet/liteflownet_pre_M5S5R5.py
configs/_base_/models/liteflownet/liteflownet_pre_M6S6.py
configs/_base_/models/liteflownet/liteflownet_pre_M6S6R6.py
configs/_base_/models/liteflownet2/liteflownet2_pre_M3S3R3.py
configs/_base_/models/liteflownet2/liteflownet2_pre_M4S4R4.py
configs/_base_/models/liteflownet2/liteflownet2_pre_M5S5R5.py
configs/_base_/models/liteflownet2/liteflownet2_pre_M6S6.py
configs/_base_/models/liteflownet2/liteflownet2_pre_M6S6R6.py
configs/_base_/models/maskflownet.py
configs/_base_/models/maskflownets.py
configs/_base_/models/pwcnet.py

1. Add  Gaussian noise for different ranks
- config/_base_/models
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:

Set diff random seed for rank

---

configs/_base_/datasets/flyingthings3d_subset_384x768.py
configs/_base_/datasets/flyingthings3d_subset_bi_with_occ_384x768.py
configs/_base_/datasets/kitti2012_kitti2015_320x896.py
configs/_base_/datasets/kitti2012_kitti2015_irr_320x896.py
configs/_base_/datasets/kitti2015_raft_288x960.py
configs/_base_/datasets/kitti2015_raft_test.py
configs/_base_/datasets/sintel_384x768.py
configs/_base_/datasets/sintel_cleanx100_sintel_fianlx100_kitti2015x200_hd1kx5_flyingthings3d_raft_384x768.py
configs/_base_/datasets/sintel_final_384x768.py
configs/_base_/datasets/sintel_final_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_final_pwcnet_384x768.py
configs/_base_/datasets/sintel_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_kitti2015_hd1k_320x768.py
configs/_base_/datasets/sintel_kitti_liteflownet2_320x768.py
configs/_base_/datasets/sintel_liteflownet_384x768.py
configs/_base_/datasets/sintel_pwcnet_384x768.py

There is no gt for test dataset, so using 'train' dataset.
1. config/_base_/datasets/
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:

Set test_mode=false for test datasets

---

mmflow/models/decoders/base_decoder.py
mmflow/models/decoders/context_net.py
mmflow/models/decoders/flownet_decoder.py
mmflow/models/decoders/gma_decoder.py
mmflow/models/decoders/irr_refine.py
mmflow/models/decoders/irrpwc_decoder.py
mmflow/models/decoders/liteflownet_decoder.py
mmflow/models/decoders/maskflownet_decoder.py
mmflow/models/decoders/pwcnet_decoder.py
mmflow/models/decoders/raft_decoder.py
mmflow/models/encoders/raft_encoder.py
mmflow/models/utils/basic_encoder.py
mmflow/models/utils/correlation_block.py
mmflow/models/utils/densenet.py
mmflow/models/utils/res_layer.py

1. Use Base Module from mmengine

[Fix] Use BaseModule from mmengien

---

configs/_base_/models/liteflownet/liteflownet_pre_M5S5R5.py

1. `data_preprocessors` -> `data_preprocessor`
1. configs/_base_/models/liteflownet/liteflownet_pre_M5S5R5.py

[Fix] Fix liteflownet cfg

---

configs/_base_/datasets/flyingthings3d_raft_400x720.py

1. configs/_base_/datasets/flyingthings3d_raft_400x720.py

[Fix] Fix Sintel test_mode in flingthings3d raft cfg

---

mmflow/datasets/transforms/formatting.py
mmflow/models/decoders/base_decoder.py

1. Add `'pad'` in default `meta_keys` in mmflow/datasets/transforms/formatting.py
2. Revise post-process to de-pad

[Fix] Fix post process for raft

---

configs/_base_/schedules/liteflownet_ft_500k.py
configs/_base_/schedules/liteflownet_ft_600k.py
configs/_base_/schedules/maskflownet_500k.py
configs/_base_/schedules/maskflownet_800k.py
configs/_base_/schedules/maskflownet_ft_1000k_schedule.py
configs/_base_/schedules/pwcnet_ft_300k_schedule.py
configs/_base_/schedules/pwcnet_plus_750k_schedule.py
configs/_base_/schedules/raft_50k.py
configs/_base_/schedules/schedule_s_fine.py
configs/_base_/schedules/schedule_s_fine_half.py
configs/_base_/schedules/schedule_s_short.py
configs/gma/gma_8x2_120k_flyingthings3d_400x720.py
configs/gma/gma_8x2_120k_flyingthings3d_sintel_368x768.py
configs/gma/gma_8x2_120k_mixed_368x768.py
configs/gma/gma_p-only_8x2_120k_flyingthings3d_400x720.py
configs/gma/gma_p-only_8x2_120k_mixed_368x768.py
configs/gma/gma_plus-p_8x2_120k_flyingthings3d_400x720.py
configs/gma/gma_plus-p_8x2_120k_mixed_368x768.py
configs/raft/raft_8x2_100k_flyingthings3d_400x720.py
configs/raft/raft_8x2_100k_flyingthings3d_sintel_368x768.py
configs/raft/raft_8x2_100k_mixed_368x768.py

1. cfg files in configs for multi-dataset testing

[Fix]  Use MultiTestLoop for test_cfg when test multiple datasets

---

configs/liteflownet/liteflownet_ft_4x1_500k_kitti_320x896.py
configs/liteflownet/liteflownet_ft_4x1_500k_sintel_384x768.py

1. configs/liteflownet/liteflownet_ft_4x1_500k_kitti_320x896.py
2. configs/liteflownet/liteflownet_ft_4x1_500k_sintel_384x768.py

[Fix] Fix liteflownet sintel and kitti finetune cfg

---

configs/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.py
configs/liteflownet2/liteflownet2_ft_4x1_600k_sintel_kitti_320x768.py

1. configs/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.py
2. configs/liteflownet2/liteflownet2_ft_4x1_600k_sintel_kitti_320x768.py

[Fix] Fix liteflownet2 sintel and kitti finetune cfg

---

configs/liteflownet/liteflownet_ft_4x1_500k_kitti_320x896.py
configs/liteflownet/liteflownet_ft_4x1_500k_sintel_384x768.py
configs/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.py
configs/liteflownet2/liteflownet2_ft_4x1_600k_sintel_kitti_320x768.py

1. configs/liteflownet/liteflownet_ft_4x1_500k_kitti_320x896.py
2. configs/liteflownet/liteflownet_ft_4x1_500k_sintel_384x768.py
3. configs/liteflownet2/liteflownet2_ft_4x1_500k_kitti_320x896.py
4. configs/liteflownet2/liteflownet2_ft_4x1_600k_sintel_kitti_320x768.py

[Fix] Fix liteflownet/liteflownet2 loss cfg when model finetuning

---

configs/_base_/datasets/sintel_kitti_liteflownet2_320x768.py

1. configs/_base_/datasets/sintel_kitti_liteflownet2_320x768.py

[Fix] dataset config for Liteflownet2 finetune

---

mmflow/datasets/sintel.py
tests/test_datasets/test_datasets.py

[Enhancement] Remove metainfo in Sintel

---

configs/_base_/schedules/maskflownet_800k.py

1. configs/_base_/schedules/maskflownet_800k.py

[Fix] Fix test_cfg and val_cfg in MaskFlownet cfg

---

mmflow/datasets/transforms/transforms.py

1. mmflow/datasets/transforms/transforms.py

[Fix] Spacial Transform

---

configs/maskflownet/maskflownets_8x1_sfine_flyingthings3d_subset_384x768.py
configs/maskflownet/maskflownets_8x1_slong_flyingchairs_384x448.py

1. configs/maskflownet/maskflownets_8x1_sfine_flyingthings3d_subset_384x768.py
2. configs/maskflownet/maskflownets_8x1_slong_flyingchairs_384x448.py

[Fix] MaskFlowNets optim

---

configs/pwcnet/metafile.yml

[Fix] Fix the metafile.yml of PWCNet

---

configs/_base_/datasets/chairssdhom_384x448.py
configs/_base_/datasets/flyingthings3d_subset_chairssdhom_384x448.py
mmflow/datasets/__init__.py
mmflow/datasets/chairssdhom.py
mmflow/datasets/samplers/distributed_sampler.py
tests/data/pseudo_chairssdhom/test.json
tests/data/pseudo_chairssdhom/train.json
tests/test_datasets/test_datasets.py
tools/prepare_datasets/prepare_chairssdhom.py

Meet the requirements of MMFlow2.0.
1. Add mmflow/datasets/chairssdom.py
2. Modify mmflow/datasets/\_\_init\_\_.py (Add ChairsSDHom related imports)
3. Modify tests/test_datasets/test_datasets.py (Add ChairsSDHom related tests)
4. Add tools/prepare_datasets/prepare_chairssdhom.py
5. Add train.json and test.json in tests/data/pseudo_chairssdhom
6. Modify configs/\_base\_/chairssdhom.py
7. Modify configs/\_base\_/flyingthings3d_subset_chairssdhom_384x448.py
8. Modify mmflow/datasets/samplers/distributed_sampler.py

[Refactor] Dataset ChairsSDHom

---

configs/_base_/schedules/maskflownet_ft_1000k_schedule.py
configs/_base_/schedules/pwcnet_ft_300k_schedule.py
configs/_base_/schedules/pwcnet_plus_750k_schedule.py
configs/_base_/schedules/schedule_s_fine.py
configs/_base_/schedules/schedule_s_fine_half.py
configs/_base_/schedules/schedule_s_short.py

1. configs/_base_/schedules/schedule_s_fine.py

[Fix] Add `default_hooks` in schedule config

---

README.md
README_zh-CN.md
docs/en/changelog.md
docs/en/faq.md
mmflow/version.py

Bump v0.5.1
1. README.md
2. README_zh-CN.md
3. docs/en/changelog.md
4. docs/en/faq.md
5. mmflow/version.py

Bump v0.5.1

---

configs/_base_/datasets/sintel_kitti2015_hd1k_320x768.py
configs/_base_/schedules/maskflownet_ft_1000k_schedule.py
configs/_base_/schedules/pwcnet_ft_300k_schedule.py
configs/_base_/schedules/pwcnet_plus_750k_schedule.py
configs/gma/metafile.yml
configs/pwcnet/metafile.yml
configs/pwcnet/pwcnet_ft_4x1_300k_kitti_320x896.py
configs/pwcnet/pwcnet_ft_4x1_300k_sintel_384x768.py
configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py
configs/pwcnet/pwcnet_plus_8x1_750k_sintel_kitti2015_hd1k_320x768.py

There are some non-standard key fields in configs and some invalid links in metafile, which lead to the failure of benchmark tests. This PR aims to fix these bugs.
1. configs/\_base\_/schedules/maskflownet_ft_1000k_schedule.py
2. configs/\_base\_/schedules/pwcnet_ft_300k_schedule.py
3. configs/\_base\_/schedules/pwcnet_plus_750k_schedule.py
1. configs/pwcnet/pwcnet_ft_4x1_300k_kitti_320x896.py
2. configs/pwcnet/pwcnet_ft_4x1_300k_sintel_384x768.py
3. configs/pwcnet/pwcnet_ft_4x1_300k_sintel_final_384x768.py
4. configs/pwcnet/pwcnet_plus_8x1_750k_sintel_kitti2015_hd1k_320x768.py
1. configs/gma/metafile.yml
2. configs/pwcnet/metafile.yml
- configs/\_base\_/datasets/sintel_kitti2015_hd1k_320x768.py

[Fix] Fix configs and metafile (for benchmark tests)

---

configs/_base_/datasets/kitti2015_raft_288x960.py
configs/_base_/schedules/raft_50k.py
configs/gma/gma_plus-p_8x2_120k_mixed_368x768.py
configs/liteflownet/metafile.yml
configs/raft/metafile.yml

There are some bugs in the configs and metafiles, leading to the failure of benchmark tests. This PR aims to fix these bugs.
1. configs/\_base\_/datasets/kitti2015_raft_288x960.py
2. configs/\_base\_/schedules/raft_50k.py
3. configs/gma/gma_plus-p_8x2_120k_mixed_368x768.py
4. configs/liteflownet/metafile.yml
5. configs/raft/metafile.yml

[Fix] Fix bugs in configs and metafiles during benchmark tests

---

.dev_scripts/benchmark_test/download_models.py
.dev_scripts/benchmark_test/test_models.py

As title.
1. Add .dev_scripts/benchmark_test/download_models.py
2. Add .dev_scripts/benchmark_test/test_models.py

[Feature] Add benchmark test scripts

---

.dev_scripts/benchmark_test/README.md
.dev_scripts/benchmark_test/test_models.py

As title.
1. .dev_scripts/benchmark_test/test_models.py
2. .dev_scripts/benchmark_test/README.md

[Docs] Add tutorial for benchmark test

---

configs/_base_/datasets/kitti2012_kitti2015_320x896.py
configs/_base_/datasets/kitti2012_kitti2015_irr_320x896.py
configs/_base_/datasets/sintel_kitti2015_hd1k_320x768.py
configs/gma/gma_8x2_50k_kitti2015_288x960.py
mmflow/datasets/transforms/transforms.py
tools/dist_train.sh

As title. Besides, there are some bugs remaining in the configs while training models. This PR aims to fix these bugs.
1. tools/dist_train.sh
2. configs/\_base\_/datasets/kitti2012_kitti2015_320x896.py
3. configs/\_base\_/datasets/kitti2012_kitti2015_irr_320x896.py
4. configs/\_base\_/datasets/sintel_kitti2015_hd1k_320x768.py
5. configs/gma/gma_8x2_50k_kitti2015_288x960.py
6. mmflow/datasets/transforms/transforms.py

[Refactor] Modify dist_train.py

---

tests/test_datasets/test_transforms/test_formatting.py
tests/test_models/test_data_preprocessor.py
tests/test_models/test_decoders/test_flownet_decoder.py
tests/test_models/test_decoders/test_gma_decoder.py
tests/test_models/test_decoders/test_irrpwc_decoder.py
tests/test_models/test_decoders/test_liteflownet_decoder.py
tests/test_models/test_decoders/test_maskflownets_decoder.py
tests/test_models/test_decoders/test_pwcnet_decoder.py
tests/test_models/test_decoders/test_raft_decoder.py
tests/test_models/test_encoders/test_basic_encoder.py

As title
FlowDataSample and BasicEncoder related imports in tests

[Fix] Fix the import error in tests

---

configs/_base_/schedules/gma_120k.py
configs/_base_/schedules/liteflownet_ft_500k.py
configs/_base_/schedules/liteflownet_ft_600k.py
configs/_base_/schedules/liteflownet_pre_240k.py
configs/_base_/schedules/liteflownet_pre_300k.py
configs/_base_/schedules/maskflownet_500k.py
configs/_base_/schedules/maskflownet_800k.py
configs/_base_/schedules/maskflownet_ft_1000k_schedule.py
configs/_base_/schedules/pwcnet_ft_300k_schedule.py
configs/_base_/schedules/pwcnet_plus_750k_schedule.py
configs/_base_/schedules/raft_100k.py
configs/_base_/schedules/raft_50k.py
configs/_base_/schedules/schedule_s_fine.py
configs/_base_/schedules/schedule_s_fine_half.py
configs/_base_/schedules/schedule_s_long.py
configs/_base_/schedules/schedule_s_short.py

1. Step is always 0, if open the `log_metric_by_epoch` in log hook
1. All log hook in config

[Fix] Record metrics in log

---

mmflow/version.py

[Fix] Update the version set of MMFlow 1.0

---

docs/en/user_guides/3_inference.md
docs/en/user_guides/4_train_test.md
tools/test.py
tools/train.py

As title.
1. docs/en/user_guides/3_inference.md
2. tools/test.py
3. tools/train.py

[Refactor] Inference tutorial for 1.x

---

mmflow/datasets/transforms/loading.py

As title
1. mmflow/datasets/transforms/loading.py

[Fix] Use FileClient from mmengine

---

docs/en/advanced_guides/transforms.md

docs/en/advanced_guides/transforms.md

[Refactor] Transforms tutorial for 1.x

---

docs/en/advanced_guides/add_transforms.md
docs/en/data_prepare/ChairsSDHom/README.md
docs/en/data_prepare/FlyingChairs/README.md
docs/en/data_prepare/FlyingChairsOcc/README.md
docs/en/data_prepare/FlyingThings3d/README.md
docs/en/data_prepare/FlyingThings3d_subset/README.md
docs/en/data_prepare/KITTI2012/README.md
docs/en/data_prepare/KITTI2015/README.md
docs/en/data_prepare/Sintel/README.md
docs/en/data_prepare/hd1k/README.md
tools/dataset_converters/prepare_chairssdhom.py
tools/dataset_converters/prepare_flyingchairs.py
tools/dataset_converters/prepare_flyingchairsocc.py
tools/dataset_converters/prepare_flyingthings3d.py
tools/dataset_converters/prepare_flyingthings3d_subset.py
tools/dataset_converters/prepare_hd1k.py
tools/dataset_converters/prepare_kitti2012.py
tools/dataset_converters/prepare_kitti2015.py
tools/dataset_converters/prepare_sintel.py

1. as title
1. docs/en/docs/en/data_prepare/
2. tools/dataset_converters/
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:

[Docs] Prepare Datasets and revise add_transforms.md

---

configs/_base_/default_runtime.py

Fix iter-based runner log processor
`configs/_base_/default_runtime.py`

[Fix] Log processor

---

configs/_base_/schedules/schedule_s_long.py

[Fix] Set `val_interval=100000` of `train_cfg` in slong

---

docs/en/advanced_guides/customize_runtime.md

As title.
`docs/en/advanced_guides/customize_runtime.md`

[Refactor] Customize runtime tutorial for 1.x

---

mmflow/__init__.py
requirements/mminstall.txt

[Enhancement] Check the version of codebase from openmmlab

---

docs/en/user_guides/visualization.md

As title.
`docs/en/user_guides/visualization.md`

[Refactor] Visualization tutorial for 1.x

---

docs/en/advanced_guides/add_modules.md

docs/en/advanced_guides/add_modules.md

[Refactor] Add modules tutorial for 1.x

---

docs/en/user_guides/1_config.md

As title.
`docs/en/user_guides/1_config.md`

[Refactor] Config tutorial for 1.x

---

docs/en/notes/changelog.md
docs/en/notes/changelog_v0.x.md

Add changelog for MMFlow 1.0.0rc0

---

docs/en/get_started.md
docs/en/notes/changelog.md

[Docs] Refine changelog

---

README.md
README_zh-CN.md

[Fix] README for 1.x

---

CONTRIBUTING.md
README.md
README_zh-CN.md

[Docs] Refine RAEDME

---

.github/workflows/pr_stage_test.yml
.pre-commit-config.yaml
docs/en/data_prepare/ChairsSDHom/README.md
docs/en/data_prepare/FlyingChairs/README.md
docs/en/data_prepare/FlyingChairsOcc/README.md
docs/en/data_prepare/FlyingThings3d/README.md
docs/en/data_prepare/FlyingThings3d_subset/README.md
docs/en/data_prepare/KITTI2012/README.md
docs/en/data_prepare/KITTI2015/README.md
docs/en/data_prepare/Sintel/README.md
docs/en/data_prepare/hd1k/README.md
setup.cfg

Update pre-commit hooks of dev-1.x

---

mmflow/datasets/utils/image.py

as title
https://numpy.org/devdocs/release/1.20.0-notes.html

[Fix] np.int is deprecated

---

mmflow/datasets/transforms/__init__.py
mmflow/datasets/transforms/loading.py
tests/test_datasets/test_transforms/test_loading.py

as title
1. mmflow/datasets/transforms/loading.py
2. tests/test_datasets/test_transforms/test_loading.py

[Feature] Add InferencerLoader
