docs_zh-CN/conf.py

1. fix links in docs_zh-CN/conf.py

[Docs]Fix wrong links to docs of project in OpenMMLab

---

mmflow/apis/__init__.py
mmflow/apis/train.py
tools/train.py

1. Add `init_random_seed` in mmflow/apis/train.py
2. Import `init_random_seed` in mmflow/apis/__init__.py
3. Revise seed setting in tools/train.py

[Enhancement] set the same seed for all rank when distributed training

---

configs/raft/metafile.yml

1. fix typo in configs/raft/metafile.yml

[Docs] fix typo in metafile

---

mmflow/models/decoders/irrpwc_decoder.py

1. mmflow/models/decoders/irrpwc_decoder.py

[Enhance] Add upsample_cfg in irr-pwc decoder

---

mmflow/models/losses/multilevel_charbonnier_loss.py
mmflow/models/losses/multilevel_epe.py
mmflow/models/losses/multilevel_flow_loss.py
tests/test_models/test_losses.py

Optical flow models always predict values of flow as ground truth resolution, even though the resolution is different at each level. This `scale_as_level` works for deciding whether to scale flow for each level at its native spatial resolution.
1. Add `scale_as_level` in `multi_level_flow_loss`
2. Add `scale_as_level` in `MultiLevelEPE`
3. Add `scale_as_level` in `class MultiLevelCharbonnierLoss`
4. Revise UT for losses function.

[Feature] Add `scale_as_level` for multi-level flow loss

---

mmflow/models/flow_estimators/raft.py

As refine iterations when model testing is different from model training, it used `test_cfg`  to modify `iter` of the model when testing but forgot to recover the `iter` for training.

[Fix] Fix RAFT wrong refine iter after evaluation

---

configs/_base_/datasets/chairssdhom_384x448.py
configs/_base_/datasets/flyingchairs_320x448.py
configs/_base_/datasets/flyingchairs_384x448.py
configs/_base_/datasets/flyingchairs_raft_368x496.py
configs/_base_/datasets/flyingchairsocc_bi_occ_384x448.py
configs/_base_/datasets/flyingthings3d_raft_400x720.py
configs/_base_/datasets/flyingthings3d_subset_384x768.py
configs/_base_/datasets/flyingthings3d_subset_bi_with_occ_384x768.py
configs/_base_/datasets/flyingthings3d_subset_chairssdhom_384x448.py
configs/_base_/datasets/kitti2012_kitti2015_320x896.py
configs/_base_/datasets/kitti2012_kitti2015_irr_320x896.py
configs/_base_/datasets/sintel_384x768.py
configs/_base_/datasets/sintel_cleanx100_sintel_fianlx100_flyingthings3d_raft_368x768.py
configs/_base_/datasets/sintel_cleanx100_sintel_fianlx100_kitti2015x200_hd1kx5_flyingthings3d_raft_384x768.py
configs/_base_/datasets/sintel_final_384x768.py
configs/_base_/datasets/sintel_final_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_final_pwcnet_384x768.py
configs/_base_/datasets/sintel_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_kitti2015_hd1k_320x768.py
configs/_base_/datasets/sintel_kitti2015_hd1k_maskflownet_320x768.py
configs/_base_/datasets/sintel_kitti_liteflownet2_320x768.py
configs/_base_/datasets/sintel_liteflownet_384x768.py
configs/_base_/datasets/sintel_pwcnet_384x768.py

`presistent_workers=True` in val_dataloader will speed up evaluation during training and not affect iter training time.

[Enhancement] Add presistent_workers=True in val_dataloader

---

configs/_base_/datasets/flyingthings3d_subset_chairssdhom_384x448.py
configs/_base_/datasets/sintel_384x768.py
configs/_base_/datasets/sintel_final_384x768.py
configs/_base_/datasets/sintel_final_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_final_pwcnet_384x768.py
configs/_base_/datasets/sintel_irr_with_occ_384x768.py
configs/_base_/datasets/sintel_pwcnet_384x768.py

1. For PWCNet, FlowNet and IRR-PWC, the input image must be dividable by 2^6
2. fix #64

[Fix] Resized input image must be dividable by 2^6

---

configs/_base_/models/raft.py
configs/raft/README.md
configs/raft/metafile.yml
configs/raft/raft_8x2_50k_kitti2015_288x960.py
tests/test_models/test_flow_estimator.py

1. As fix the bug in RAFT decoder https://github.com/open-mmlab/mmflow/pull/62, the model has been retrained.
2. Use `SyncBN` to improve the performance.
3. Release model fine-tuned on KITTI2015

[Enhancement] Update RAFT model

---

mmflow/apis/train.py
mmflow/utils/__init__.py
mmflow/utils/misc.py
tests/test_utils/test_misc.py
tools/train.py

1. Add `find_latest_checkpoint` which will be used when auto-resume training
2. Add argument `auto-resume` in tools/train.py
Related PR: https://github.com/open-mmlab/mmdetection/pull/6727/files

[Features] Support auto-resume

---

tools/test.py
tools/train.py

Since MMDP does not support non-distributed multi-GPU training, --gpus in train.py lost its role, so it is removed, --gpu-ids is changed to --gpu-id, because only one GPU can be specified for non-distribution training and testing.
If the number of GPUs is more than 1, there will be an assertion error in MMDP because MMDP does not support the situation with more than one GPU.
ref : https://github.com/open-mmlab/mmdetection/pull/7019

Fix bug in non-distributed multi-gpu training/testing

---

.github/workflows/build.yml
docs/en/install.md

mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well.
Refer to https://github.com/open-mmlab/mmtracking/pull/409
modify build.yml
modify install.md

[Enhancement] Update the installation of MMCV

---

mmflow/models/losses/__init__.py
mmflow/models/losses/smooth_loss.py
tests/test_models/test_losses.py

as tittle
- add mmflow/models/losses/smooth_loss.py

[Features] Add smoothness loss function

---

configs/pwcnet/pwcnet_plus_8x1_750k_sintel_kitti2015_hd1k_320x768.py

add pretrained pwc-model when finetune on mix-dataset [kitti2015/sintel/hd1k]

[FIX] Add pretrained pwc-model when train pwc-plus

---

mmflow/core/utils/__init__.py
mmflow/core/utils/dist_utils.py
mmflow/datasets/builder.py
mmflow/datasets/samplers/distributed_sampler.py

as title 
ref: https://github.com/open-mmlab/mmdetection/pull/7432 and https://github.com/open-mmlab/mmdetection/pull/7440

[Fix] Sync seed for dist sampler

---

mmflow/utils/collect_env.py
tests/test_utils/test_set_env.py

1. Add try-except block when checking gcc version for Windows platform

[Enhancement]Revise collect_env for win platform

---

mmflow/apis/train.py
tools/test.py

https://github.com/open-mmlab/mmclassification/pull/752
1. Add overall dataloader cfg in api/train.py
2. Add overall dataloader cfg in tools/test.py

[Enhancement] Support overall dastaloader settings

---

configs/pwcnet/metafile.yml

The config and weights are not corresponding in the metafile.yml
Revise the metafile from pwcnet

[Fix] The config and weights are not corresponding in the metafile.yml

---

docs/en/conf.py
docs/zh_cn/conf.py
requirements/docs.txt

Use myst_parser instead of remomonmark
1. revise requirements/docs.txt
2. revise conf.py

[Fix]Replace recommonmark wiht myst_parser

---

.github/workflows/build.yml
demo/image_demo.py
mmflow/apis/inference.py
tests/test_apis/test_inference.py

[Fix] Inference bug for sparse flow map

---

configs/_base_/datasets/sintel_kitti2015_hd1k_320x768.py

Fix https://github.com/open-mmlab/mmflow/issues/135

[Fix] H and W input images must be divisible by 2**6

---

configs/flownet2/README.md
configs/flownet2/flownet2_8x1_slong_flyingchairs_384x448.py
configs/flownet2/flownet2css_8x1_sfine_flyingthings3d_subset_384x768.py
configs/flownet2/metafile.yml

Add config and pre-trained model for flownet2 on FlyingChairs.
1. Add configs/flownet2/flownet2_8x1_slong_flyingchairs_384x448.py
2. Fix configs/flownet2/metafile.yml
3. Fix configs/flownet2/REDAME.md
4. Fix configs/flownet2/flownet2css_8x1_sfine_flyingthings3d_subset_384x768.py

[Feature] Add config and pre-trained model for flownet2 on FlyingChairs

---

mmflow/models/decoders/base_decoder.py

We use interpolations to resize the predicted optical flows to recover original shapes.  However, the final results are wrong due to the order of dimensions has changed compared to mmflow1.0. This PR aims to fix the bug.
- mmflow/models/decoders/base_decoder.py

[Fix] Fix the bug of postprocess

---

mmflow/models/decoders/raft_decoder.py
mmflow/models/utils/attention.py
mmflow/models/utils/attention1d.py
tests/test_models/test_utils/test_attention.py

It is a module to compute attention (both self attention and cross attention)
Add mmflow/models/utils/attention.py
Add tests/test_models/test_utils/test_attention.py
Input: feature1 [b,c,h,w] feature2 [b,c,h,w]
Output: self-attention-x [b,c,h,w] self-attention-y [b,c,h,w]
cross-attention-y [b,c,h,w] attention-y [b,w,h,h]
cross-attention-x [b,c,h,w] attention-x [b,h,w,w]

[Feature] Add flow1d attention

---

configs/raft/README.md
configs/raft/metafile.yml

The config raft_8x2_50k_kitti2015_288x960 related URLs in README.md and metafile.yml are wrong, which may cause confusions.
1. configs/raft/README.md
2. configs/raft/metafile.yml
Rename the files in cloud:
1. `raft_8x2_50k_kitti2015_368x768.log.json` -> `raft_8x2_50k_kitti2015_288x960.log.json`
2. `raft_8x2_50k_kitti2015_368x768.py` -> `raft_8x2_50k_kitti2015_288x960.py`
3. `raft_8x2_50k_kitti2015_368x768.pth` -> `raft_8x2_50k_kitti2015_288x960.pth`

[Fix] Fix some URLs of RAFT

---

configs/liteflownet/metafile.yml
configs/raft/README.md
configs/raft/metafile.yml

The config raft_8x2_50k_kitti2015_288x960 related URLs in README.md and metafile.yml are wrong, which may cause confusions.
1. configs/raft/README.md
2. configs/raft/metafile.yml
3. configs/liteflownet/metafile.yml
Rename the files in cloud:
1. `raft_8x2_50k_kitti2015_368x768.log.json` -> `raft_8x2_50k_kitti2015_288x960.log.json`
2. `raft_8x2_50k_kitti2015_368x768.py` -> `raft_8x2_50k_kitti2015_288x960.py`
4. `raft_8x2_50k_kitti2015_368x768.pth` -> `raft_8x2_50k_kitti2015_288x960.pth`

[Fix] Fix some URLs of RAFT(MMFlow 1.0)

---

configs/_base_/datasets/kitti2012_kitti2015_320x896.py
configs/_base_/datasets/kitti2012_kitti2015_irr_320x896.py
configs/_base_/datasets/kitti2015_raft_288x960.py
configs/_base_/datasets/sintel_kitti_liteflownet2_320x768.py

The original configs of KITTI evaluator are redundant. This PR aims to fix them.
The visualization of training logs has already modified in this [PR](https://github.com/open-mmlab/mmflow/pull/208), seen in the [file](https://github.com/open-mmlab/mmflow/blob/1f6055d32a2bb2ebe7e7d3d0c1fa2739136333a6/tools/analysis_tools/analyze_logs.py).
1. configs/\_base\_/datasets/kitti2012_kitti2015_320x896.py
2. configs/\_base\_/datasets/kitti2012_kitti2015_irr_320x896.py
3. configs/\_base\_/datasets/kitti2015_raft_288x960.py
4. configs/\_base\_/datasets/sintel_kitti_liteflownet2_320x768.py

[Fix] Fix the prefix of kitti evaluator

---

tests/test_datasets/test_transforms/test_advanced_transform.py
tests/test_datasets/test_transforms/test_loading.py
tests/test_datasets/test_transforms/test_transforms.py

The changes of file structures result in the change of relative path, leading to the failure of UT.
1. tests/test_datasets/test_transforms/test_advanced_transform.py
2. tests/test_datasets/test_transforms/test_loading.py
3. tests/test_datasets/test_transforms/test_transforms.py

[Fix] Fix the relative paths in tests

---

mmflow/datasets/chairssdhom.py
mmflow/datasets/flyingchairs.py
mmflow/datasets/flyingchairsocc.py
mmflow/datasets/flyingthings3d.py
mmflow/datasets/flyingthings3d_subset.py
tests/test_datasets/test_datasets.py

The differences in metainfo might lead to failure when building  `ConcatDataset`. Thus, this PR aims to delete phase related information in metainfo.
Delete the `subset` field in mmflow/datasets and tests/test_datasets

[Fix] Delete phase info in metainfo

---

configs/_base_/datasets/sintel_final_irr_with_occ_384x768.py
configs/irr/irrpwc_ft_4x1_300k_kitti_320x896.py
configs/irr/irrpwc_ft_4x1_300k_sintel_384x768.py
configs/irr/irrpwc_ft_4x1_300k_sintel_final_384x768.py
mmflow/apis/inference.py

The updated config might cause conflicts during inference. Plus, the configs of irr lack of `data_preprocessor`.
1. configs/\_base\_/datasets/sintel_final_irr_with_occ_384x768.py
2. configs/irr/irrpwc_ft_4x1_300k_kitti_320x896.py
3. configs/irr/irrpwc_ft_4x1_300k_sintel_384x768.py
4. configs/irr/irrpwc_ft_4x1_300k_sintel_final_384x768.py
5. mmflow/apis/inference.py

[Fix] Fix bugs in inference and configs

---

docs/en/advanced_guides/add_modules.md
docs/en/advanced_guides/customize_runtime.md
docs/en/intro.md
docs/en/user_guides/1_config.md
docs/en/user_guides/3_inference.md
docs/en/user_guides/4_train_test.md
docs/en/user_guides/visualization.md

As title.
1. Links related to `mmengine` documentation.
2. The relative path of the document is changed to a URL link.

[Fix] Update the links in tutorials

---

mmflow/models/utils/res_layer.py

In Issue #248, there is a bug when fine-tuning RAFT, which is caused by an inappropriate in-place operator. This PR aims to fix this bug.
`mmflow/models/utils/res_layer.py`

[Fix] Fix in-place operator in RAFT

---

.pre-commit-config.yaml
mmflow/datasets/pipelines/transforms.py
setup.cfg

Update pre-commit hooks of master branch

---

requirements/optional.txt

[Fix]The `sklearn` PyPI package is deprecated, use `scikit-learn`
